## Basic Configuration

baseurl = "https://tmasjc.github.io/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"

author = "tmasjc"
title = "Thomas Jc"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
# googleAnalytics = "XYZ"
# enableRobotsTXT = true

## Site Settings
[params]
author = "Thomas Jc"
intro1 = "Business Intelligence Analyst"
intro2 = "Machine Learning Engineer"
description = "Currently Head of Analytics & Strategy @Belvedor (住百家)"
authorimage = "profile.JPG"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Thomas's personal site"
keywords = "tmasjc, data, analyst, hugo"

## Social Accounts
[params.social]
github = "tmasjc"
linkedin = ""
email = "thomas.jcng@gmail.com"

## Extras
[params.extra]
copyright = "© 2017. Thomas Jc (tmasjc) All Rights Reserved"
poweredby = true
highlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/"
